sudo: required

language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  # Build the docker container and tag it with the name 'twci/docker-react'
  - docker build -t twci/docker-react -f Dockerfile.dev .

scripts:
  # Run the tests
  - docker run twci/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-828354061337'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
